// TrackingServiceTests.swift
// LiquidEditorTests
//
// Comprehensive tests for TrackingService:
// - Session lifecycle (create, cancel, remove)
// - Available algorithms listing
// - Invalid algorithm handling
// - Session results queries (null when no session)
// - Quality metrics computation
// - Progress event structure validation
// - TrackingQualityMetrics structure
// - TrackingProgressEvent structure

import Testing
import Foundation
import CoreMedia
@testable import LiquidEditor

// MARK: - TrackingService Tests

@Suite("TrackingService Tests")
struct TrackingServiceTests {

    // MARK: - Initialization

    @Test("Service initializes with available algorithms")
    func initialization() async {
        let service = TrackingService()
        let algorithms = await service.availableAlgorithms()
        #expect(!algorithms.isEmpty)
    }

    @Test("BoundingBox algorithm is available")
    func boundingBoxAvailable() async {
        let service = TrackingService()
        let algorithms = await service.availableAlgorithms()
        let hasBoundingBox = algorithms.contains { $0.id == "boundingBox" }
        #expect(hasBoundingBox == true)
    }

    @Test("BoundingBox algorithm supports multiple people")
    func boundingBoxSupportsMultiple() async {
        let service = TrackingService()
        let algorithms = await service.availableAlgorithms()
        let bb = algorithms.first { $0.id == "boundingBox" }
        #expect(bb?.supportsMultiplePeople == true)
    }

    // MARK: - Invalid Algorithm

    @Test("Analyze with unknown algorithm yields error progress event")
    func unknownAlgorithm() async {
        let service = TrackingService()
        let (sessionId, stream) = await service.analyzeVideo(
            path: "/tmp/nonexistent.mp4",
            algorithm: "unknownAlgo",
            sessionId: "test-session-unknown"
        )

        #expect(!sessionId.isEmpty)

        var events: [TrackingProgressEvent] = []
        for await event in stream {
            events.append(event)
        }

        // Should have at least one error event
        let hasError = events.contains { $0.error != nil }
        #expect(hasError == true)

        let errorEvent = events.first { $0.error != nil }
        #expect(errorEvent?.progress == -1)
        #expect(errorEvent?.error?.contains("Unknown algorithm") == true)
    }

    // MARK: - Session ID

    @Test("Client-provided session ID is used")
    func clientSessionId() async {
        let service = TrackingService()
        let (sessionId, _) = await service.analyzeVideo(
            path: "/tmp/nonexistent.mp4",
            algorithm: "unknownAlgo",
            sessionId: "my-custom-id"
        )

        #expect(sessionId == "my-custom-id")
    }

    @Test("Auto-generated session ID is a valid UUID string")
    func autoGeneratedSessionId() async {
        let service = TrackingService()
        let (sessionId, _) = await service.analyzeVideo(
            path: "/tmp/nonexistent.mp4",
            algorithm: "unknownAlgo"
        )

        #expect(!sessionId.isEmpty)
        // UUID strings have 36 characters (8-4-4-4-12)
        #expect(sessionId.count == 36)
    }

    // MARK: - Cancel Session

    @Test("Cancel analysis removes session data")
    func cancelSession() async {
        let service = TrackingService()
        let (sessionId, _) = await service.analyzeVideo(
            path: "/tmp/test.mp4",
            algorithm: "boundingBox",
            sessionId: "cancel-test"
        )

        await service.cancelAnalysis(sessionId: sessionId)

        // After cancellation, results should be nil
        let results = await service.getAllResults(sessionId: sessionId)
        #expect(results == nil)
    }

    // MARK: - Remove Session

    @Test("Remove session clears all associated data")
    func removeSession() async {
        let service = TrackingService()
        let (sessionId, _) = await service.analyzeVideo(
            path: "/tmp/test.mp4",
            algorithm: "boundingBox",
            sessionId: "remove-test"
        )

        await service.removeSession(sessionId)

        let results = await service.getAllResults(sessionId: sessionId)
        #expect(results == nil)

        let persons = await service.getDetectedPersons(sessionId: sessionId)
        #expect(persons == nil)

        let metrics = await service.getQualityMetrics(sessionId: sessionId)
        #expect(metrics == nil)
    }

    // MARK: - Results Queries for Nonexistent Session

    @Test("Get results for nonexistent session returns nil")
    func resultsNonexistent() async {
        let service = TrackingService()
        let results = await service.getAllResults(sessionId: "nonexistent")
        #expect(results == nil)
    }

    @Test("Get interpolated result for nonexistent session returns nil")
    func interpolatedNonexistent() async {
        let service = TrackingService()
        let result = await service.getInterpolatedResult(sessionId: "nonexistent", timestampMs: 0)
        #expect(result == nil)
    }

    @Test("Get detected persons for nonexistent session returns nil")
    func detectedPersonsNonexistent() async {
        let service = TrackingService()
        let persons = await service.getDetectedPersons(sessionId: "nonexistent")
        #expect(persons == nil)
    }

    @Test("Get quality metrics for nonexistent session returns nil")
    func metricsNonexistent() async {
        let service = TrackingService()
        let metrics = await service.getQualityMetrics(sessionId: "nonexistent")
        #expect(metrics == nil)
    }

    @Test("Export tracking data for nonexistent session returns nil")
    func exportNonexistent() async throws {
        let service = TrackingService()
        let data = try await service.exportTrackingData(sessionId: "nonexistent")
        #expect(data == nil)
    }

    @Test("Extract person thumbnail for nonexistent session returns nil")
    func thumbnailNonexistent() async {
        let service = TrackingService()
        let data = await service.extractPersonThumbnail(
            sessionId: "nonexistent",
            personIndex: 0,
            videoPath: "/tmp/test.mp4"
        )
        #expect(data == nil)
    }

    // MARK: - Merge Statistics

    @Test("Merge statistics for nonexistent session returns nil")
    func mergeStatsNonexistent() async {
        let service = TrackingService()
        let stats = await service.getMergeStatistics(for: "nonexistent")
        #expect(stats == nil)
    }

    // MARK: - People Library

    @Test("Set and clear people library does not crash")
    func peopleLibrary() async {
        let service = TrackingService()
        await service.setPeopleLibrary([])
        await service.clearPeopleLibrary()
    }

    // MARK: - Analyze with nonexistent file yields error

    @Test("Analyze nonexistent file yields error event in stream")
    func analyzeNonexistentFile() async {
        let service = TrackingService()
        let (_, stream) = await service.analyzeVideo(
            path: "/tmp/this_file_does_not_exist_at_all.mp4",
            algorithm: "boundingBox",
            sessionId: "nonexistent-file-test"
        )

        var events: [TrackingProgressEvent] = []
        for await event in stream {
            events.append(event)
        }

        // Should get at least one event (either initial progress or error)
        #expect(!events.isEmpty)

        // The last meaningful event should indicate an error (negative progress)
        let hasError = events.contains { $0.progress < 0 }
        #expect(hasError == true)
    }
}

// MARK: - TrackingProgressEvent Tests

@Suite("TrackingProgressEvent Tests")
struct TrackingProgressEventTests {

    @Test("Progress event stores values correctly")
    func basicCreation() {
        let event = TrackingProgressEvent(
            sessionId: "s1",
            progress: 0.5,
            error: nil,
            debugInfo: "test info"
        )
        #expect(event.sessionId == "s1")
        #expect(event.progress == 0.5)
        #expect(event.error == nil)
        #expect(event.debugInfo == "test info")
    }

    @Test("Error event has negative progress")
    func errorEvent() {
        let event = TrackingProgressEvent(
            sessionId: "s1",
            progress: -1,
            error: "Something went wrong"
        )
        #expect(event.progress < 0)
        #expect(event.error != nil)
    }

    @Test("Default parameters work correctly")
    func defaults() {
        let event = TrackingProgressEvent(sessionId: "s1", progress: 0.3)
        #expect(event.error == nil)
        #expect(event.debugInfo == nil)
    }
}

// MARK: - TrackingQualityMetrics Tests

@Suite("TrackingQualityMetrics Tests")
struct TrackingQualityMetricsTests {

    @Test("Quality metrics stores all fields")
    func basicCreation() {
        let metrics = TrackingQualityMetrics(
            averageConfidence: 0.85,
            trackingStability: 0.92,
            totalFrames: 100,
            trackedFrames: 92,
            gapFilledFrames: 5
        )

        #expect(metrics.averageConfidence == 0.85)
        #expect(metrics.trackingStability == 0.92)
        #expect(metrics.totalFrames == 100)
        #expect(metrics.trackedFrames == 92)
        #expect(metrics.gapFilledFrames == 5)
    }

    @Test("Perfect metrics have stability of 1.0")
    func perfectMetrics() {
        let metrics = TrackingQualityMetrics(
            averageConfidence: 1.0,
            trackingStability: 1.0,
            totalFrames: 50,
            trackedFrames: 50,
            gapFilledFrames: 0
        )

        #expect(metrics.trackingStability == 1.0)
        #expect(metrics.gapFilledFrames == 0)
    }
}
